services:
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    volumes:
      - ./todo-frontend:/usr/src/app
      # Prevents overwriting node_modules in the container
      # This is necessary when using mac and linux containers together
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
    container_name: todo-frontend-dev
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    depends_on:
      - app